package com.stockapp.stockserver.entity;

import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "BizDate")
public class BizDate extends BaseEntity {
	@Id
	@Column(name = "bizDate", unique = true, nullable = false)
	private LocalDate bizDate;
	
	//當天狀態 0:放假 1:上班
	@Column(name = "dateType", nullable = false)
	private Integer dayType;
	
	public BizDate() {
	}

	public LocalDate getBizDate() {
		return bizDate;
	}

	public void setBizDate(LocalDate bizDate) {
		this.bizDate = bizDate;
	}

	public Integer getDayType() {
		return dayType;
	}

	public void setDayType(Integer dayType) {
		this.dayType = dayType;
	}


}
