package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "FuturesOpen")
public class FuturesOpen extends BaseEntity {

	//紀錄資料為data的time值(long)，皆以當天早上8:00為時間標準
	@Id
	@Column(name = "dataTime", nullable = false)
	private Long dataTime;
	
	/** 時間*/
	@Column(name = "dataDate")
	private Date dataDate;

	//買前五大交易人合計
	@Column(name = "buyMonthTop5")
	private Integer buyMonthTop5;

	//買前十大交易人合計
	@Column(name = "buyMonthTop10")
	private Integer buyMonthTop10;

	//買前五大交易人合計 特定法人
	@Column(name = "buyMonthTop5S")
	private Integer buyMonthTop5S;

	//買前十大交易人合計 特定法人
	@Column(name = "buyMonthTop10S")
	private Integer buyMonthTop10S;

	//買前五大交易人合計 所有契約
	@Column(name = "buyAllTop5")
	private Integer buyAllTop5;

	//買前十大交易人合計 所有契約
	@Column(name = "buyAllTop10")
	private Integer buyAllTop10;

	//買前五大交易人合計 特定法人 所有契約
	@Column(name = "buyAllTop5S")
	private Integer buyAllTop5S;

	//買前十大交易人合計 特定法人 所有契約
	@Column(name = "buyAllTop10S")
	private Integer buyAllTop10S;

	//賣前五大交易人合計
	@Column(name = "sellMonthTop5")
	private Integer sellMonthTop5;

	//賣前十大交易人合計
	@Column(name = "sellMonthTop10")
	private Integer sellMonthTop10;

	//賣前五大交易人合計 特定法人
	@Column(name = "sellMonthTop5S")
	private Integer sellMonthTop5S;

	//賣前十大交易人合計 特定法人
	@Column(name = "sellMonthTop10S")
	private Integer sellMonthTop10S;

	//賣前五大交易人合計 所有契約
	@Column(name = "sellAllTop5")
	private Integer sellAllTop5;

	//賣前十大交易人合計 所有契約
	@Column(name = "sellAllTop10")
	private Integer sellAllTop10;

	//賣前五大交易人合計 特定法人 所有契約
	@Column(name = "sellAllTop5S")
	private Integer sellAllTop5S;

	//賣前十大交易人合計 特定法人 所有契約
	@Column(name = "sellAllTop10S")
	private Integer sellAllTop10S;

	//全市場未沖銷部位數 月
	@Column(name = "monthTotalOpen")
	private Integer monthTotalOpen;

	//全市場未沖銷部位數 所有
	@Column(name = "allTotalOpen")
	private Integer allTotalOpen;

	//多方 自營 未平倉
	@Column(name = "buyOpens1")
	private Integer buyOpens1;

	//空方 自營 未平倉
	@Column(name = "sellOpens1")
	private Integer sellOpens1;

	//多方 投信 未平倉
	@Column(name = "buyOpens2")
	private Integer buyOpens2;

	//空方 投信 未平倉
	@Column(name = "sellOpens2")
	private Integer sellOpens2;

	//多方 外資 未平倉
	@Column(name = "buyOpens3")
	private Integer buyOpens3;

	//空方 外資 未平倉
	@Column(name = "sellOpens3")
	private Integer sellOpens3;

	//多方 自營 未平倉 小型
	@Column(name = "buyOpens1Small")
	private Integer buyOpens1Small;

	//空方 自營 未平倉 小型
	@Column(name = "sellOpens1Small")
	private Integer sellOpens1Small;

	//多方 投信 未平倉 小型
	@Column(name = "buyOpens2Small")
	private Integer buyOpens2Small;

	//空方 投信 未平倉 小型
	@Column(name = "sellOpens2Small")
	private Integer sellOpens2Small;

	//多方 外資 未平倉 小型
	@Column(name = "buyOpens3Small")
	private Integer buyOpens3Small;

	//空方 外資 未平倉 小型
	@Column(name = "sellOpens3Small")
	private Integer sellOpens3Small;

	
	public FuturesOpen() {
	}


	public Long getDataTime() {
		return dataTime;
	}


	public void setDataTime(Long dataTime) {
		this.dataTime = dataTime;
	}


	public Date getDataDate() {
		return dataDate;
	}


	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}


	public Integer getBuyMonthTop5() {
		return buyMonthTop5;
	}


	public void setBuyMonthTop5(Integer buyMonthTop5) {
		this.buyMonthTop5 = buyMonthTop5;
	}


	public Integer getBuyMonthTop10() {
		return buyMonthTop10;
	}


	public void setBuyMonthTop10(Integer buyMonthTop10) {
		this.buyMonthTop10 = buyMonthTop10;
	}


	public Integer getBuyMonthTop5S() {
		return buyMonthTop5S;
	}


	public void setBuyMonthTop5S(Integer buyMonthTop5S) {
		this.buyMonthTop5S = buyMonthTop5S;
	}


	public Integer getBuyMonthTop10S() {
		return buyMonthTop10S;
	}


	public void setBuyMonthTop10S(Integer buyMonthTop10S) {
		this.buyMonthTop10S = buyMonthTop10S;
	}


	public Integer getBuyAllTop5() {
		return buyAllTop5;
	}


	public void setBuyAllTop5(Integer buyAllTop5) {
		this.buyAllTop5 = buyAllTop5;
	}


	public Integer getBuyAllTop10() {
		return buyAllTop10;
	}


	public void setBuyAllTop10(Integer buyAllTop10) {
		this.buyAllTop10 = buyAllTop10;
	}


	public Integer getBuyAllTop5S() {
		return buyAllTop5S;
	}


	public void setBuyAllTop5S(Integer buyAllTop5S) {
		this.buyAllTop5S = buyAllTop5S;
	}


	public Integer getBuyAllTop10S() {
		return buyAllTop10S;
	}


	public void setBuyAllTop10S(Integer buyAllTop10S) {
		this.buyAllTop10S = buyAllTop10S;
	}


	public Integer getSellMonthTop5() {
		return sellMonthTop5;
	}


	public void setSellMonthTop5(Integer sellMonthTop5) {
		this.sellMonthTop5 = sellMonthTop5;
	}


	public Integer getSellMonthTop10() {
		return sellMonthTop10;
	}


	public void setSellMonthTop10(Integer sellMonthTop10) {
		this.sellMonthTop10 = sellMonthTop10;
	}


	public Integer getSellMonthTop5S() {
		return sellMonthTop5S;
	}


	public void setSellMonthTop5S(Integer sellMonthTop5S) {
		this.sellMonthTop5S = sellMonthTop5S;
	}


	public Integer getSellMonthTop10S() {
		return sellMonthTop10S;
	}


	public void setSellMonthTop10S(Integer sellMonthTop10S) {
		this.sellMonthTop10S = sellMonthTop10S;
	}


	public Integer getSellAllTop5() {
		return sellAllTop5;
	}


	public void setSellAllTop5(Integer sellAllTop5) {
		this.sellAllTop5 = sellAllTop5;
	}


	public Integer getSellAllTop10() {
		return sellAllTop10;
	}


	public void setSellAllTop10(Integer sellAllTop10) {
		this.sellAllTop10 = sellAllTop10;
	}


	public Integer getSellAllTop5S() {
		return sellAllTop5S;
	}


	public void setSellAllTop5S(Integer sellAllTop5S) {
		this.sellAllTop5S = sellAllTop5S;
	}


	public Integer getSellAllTop10S() {
		return sellAllTop10S;
	}


	public void setSellAllTop10S(Integer sellAllTop10S) {
		this.sellAllTop10S = sellAllTop10S;
	}


	public Integer getMonthTotalOpen() {
		return monthTotalOpen;
	}


	public void setMonthTotalOpen(Integer monthTotalOpen) {
		this.monthTotalOpen = monthTotalOpen;
	}


	public Integer getAllTotalOpen() {
		return allTotalOpen;
	}


	public void setAllTotalOpen(Integer allTotalOpen) {
		this.allTotalOpen = allTotalOpen;
	}


	public Integer getBuyOpens1() {
		return buyOpens1;
	}


	public void setBuyOpens1(Integer buyOpens1) {
		this.buyOpens1 = buyOpens1;
	}


	public Integer getSellOpens1() {
		return sellOpens1;
	}


	public void setSellOpens1(Integer sellOpens1) {
		this.sellOpens1 = sellOpens1;
	}


	public Integer getBuyOpens2() {
		return buyOpens2;
	}


	public void setBuyOpens2(Integer buyOpens2) {
		this.buyOpens2 = buyOpens2;
	}


	public Integer getSellOpens2() {
		return sellOpens2;
	}


	public void setSellOpens2(Integer sellOpens2) {
		this.sellOpens2 = sellOpens2;
	}


	public Integer getBuyOpens3() {
		return buyOpens3;
	}


	public void setBuyOpens3(Integer buyOpens3) {
		this.buyOpens3 = buyOpens3;
	}


	public Integer getSellOpens3() {
		return sellOpens3;
	}


	public void setSellOpens3(Integer sellOpens3) {
		this.sellOpens3 = sellOpens3;
	}


	public Integer getBuyOpens1Small() {
		return buyOpens1Small;
	}


	public void setBuyOpens1Small(Integer buyOpens1Small) {
		this.buyOpens1Small = buyOpens1Small;
	}


	public Integer getSellOpens1Small() {
		return sellOpens1Small;
	}


	public void setSellOpens1Small(Integer sellOpens1Small) {
		this.sellOpens1Small = sellOpens1Small;
	}


	public Integer getBuyOpens2Small() {
		return buyOpens2Small;
	}


	public void setBuyOpens2Small(Integer buyOpens2Small) {
		this.buyOpens2Small = buyOpens2Small;
	}


	public Integer getSellOpens2Small() {
		return sellOpens2Small;
	}


	public void setSellOpens2Small(Integer sellOpens2Small) {
		this.sellOpens2Small = sellOpens2Small;
	}


	public Integer getBuyOpens3Small() {
		return buyOpens3Small;
	}


	public void setBuyOpens3Small(Integer buyOpens3Small) {
		this.buyOpens3Small = buyOpens3Small;
	}


	public Integer getSellOpens3Small() {
		return sellOpens3Small;
	}


	public void setSellOpens3Small(Integer sellOpens3Small) {
		this.sellOpens3Small = sellOpens3Small;
	}

}
