package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "MailTarget")
public class MailTarget extends BaseEntity {
	@Id
	@Column(name = "email", unique = true, nullable = false)
	private String email;

	@Column(name = "target", length=1000, unique = true, nullable = false)
	private String target;
	
	public MailTarget() {
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getTarget() {
		return target;
	}


	public void setTarget(String target) {
		this.target = target;
	}


}
