package com.stockapp.stockserver.entity;


import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu")
public class Menu extends BaseEntity implements Comparable<Menu> {

	private String id;
	private String name;
	private String url;
	private String parentId;
	private String sequence;
	private Menu parent;
	private int enabled;
	private List<Menu> children;

	public Menu() {
	}

	public Menu(String id) {
		this.id = id;
	}

	public Menu(String id, String name, String url, String parentId,
			String sequence) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.parentId = parentId;
		this.sequence = sequence;
	}
	public Menu(Menu src) {
		this.id = src.id;
		this.name = src.name;
		this.url = src.url;
		this.sequence = src.sequence;
		this.parentId = src.parentId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "parent_id", length = 20)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "sequence", length = 4)
	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", updatable = false, insertable = false)
	public Menu getParent() {
		return parent;
	}

	public void setParent(Menu parent) {
		this.parent = parent;
	}

	@OneToMany(mappedBy = "parent", fetch = FetchType.LAZY)
	public List<Menu> getChildren() {
		return children;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}

	@Column(name = "enabled")
	public int getEnabled() {
		return enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	@Override
	public int compareTo(Menu target) {
		if (target == null) {
			return 1;
		}
		
		if (sequence == null || sequence.compareTo(target.sequence) > 0) {
			return 1;
		}

		if (sequence.compareTo(target.sequence) < 0) {
			return -1;
		}

		if (this.id == null) {
			return -1;
		}

		if (target.id == null) {
			return 1;
		}

		return this.id.compareTo(target.id);
	}
}
