package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "OptionsOpen")
public class OptionsOpen extends BaseEntity {
	@EmbeddedId
	private OptionsOpenId id;
	
	/** 時間*/
	@Column(name = "dataDate")
	private Date dataDate;

	//買call未平倉量
	@Column(name = "bCallOI")
	private Integer bCallOI;

	//買call總金額
	@Column(name = "bCallTotalPrice")
	private Integer bCallTotalPrice;

	//買call均價
	@Column(name = "bCallAvgPrice")
	private Double bCallAvgPrice;

	//買call與前一天差額
	@Column(name = "bCallDiff")
	private Integer bCallDiff;

	//買put未平倉量
	@Column(name = "bPutOI")
	private Integer bPutOI;

	//買put總金額
	@Column(name = "bPutTotalPrice")
	private Integer bPutTotalPrice;

	//買put均價
	@Column(name = "bPutAvgPrice")
	private Double bPutAvgPrice;

	//買put與前一天差額
	@Column(name = "bPutDiff")
	private Integer bPutDiff;

	//賣call未平倉量
	@Column(name = "sCallOI")
	private Integer sCallOI;

	//賣call總金額
	@Column(name = "sCallTotalPrice")
	private Integer sCallTotalPrice;

	//賣call均價
	@Column(name = "sCallAvgPrice")
	private Double sCallAvgPrice;

	//賣call與前一天差額
	@Column(name = "sCallDiff")
	private Integer sCallDiff;

	//賣put未平倉量
	@Column(name = "sPutOI")
	private Integer sPutOI;

	//賣put總金額
	@Column(name = "sPutTotalPrice")
	private Integer sPutTotalPrice;

	//賣put均價
	@Column(name = "sPutAvgPrice")
	private Double sPutAvgPrice;

	//賣put與前一天差額
	@Column(name = "sPutDiff")
	private Integer sPutDiff;
	

	public OptionsOpenId getId() {
		return id;
	}


	public void setId(OptionsOpenId id) {
		this.id = id;
	}


	public Integer getbCallOI() {
		return bCallOI;
	}


	public void setbCallOI(Integer bCallOI) {
		this.bCallOI = bCallOI;
	}


	public Integer getbCallTotalPrice() {
		return bCallTotalPrice;
	}


	public void setbCallTotalPrice(Integer bCallTotalPrice) {
		this.bCallTotalPrice = bCallTotalPrice;
	}


	public Double getbCallAvgPrice() {
		return bCallAvgPrice;
	}


	public void setbCallAvgPrice(Double bCallAvgPrice) {
		this.bCallAvgPrice = bCallAvgPrice;
	}


	public Integer getbCallDiff() {
		return bCallDiff;
	}


	public void setbCallDiff(Integer bCallDiff) {
		this.bCallDiff = bCallDiff;
	}


	public Integer getbPutOI() {
		return bPutOI;
	}


	public void setbPutOI(Integer bPutOI) {
		this.bPutOI = bPutOI;
	}


	public Integer getbPutTotalPrice() {
		return bPutTotalPrice;
	}


	public void setbPutTotalPrice(Integer bPutTotalPrice) {
		this.bPutTotalPrice = bPutTotalPrice;
	}


	public Double getbPutAvgPrice() {
		return bPutAvgPrice;
	}


	public void setbPutAvgPrice(Double bPutAvgPrice) {
		this.bPutAvgPrice = bPutAvgPrice;
	}


	public Integer getbPutDiff() {
		return bPutDiff;
	}


	public void setbPutDiff(Integer bPutDiff) {
		this.bPutDiff = bPutDiff;
	}


	public Date getDataDate() {
		return dataDate;
	}


	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}


	public Integer getsCallOI() {
		return sCallOI;
	}


	public void setsCallOI(Integer sCallOI) {
		this.sCallOI = sCallOI;
	}


	public Integer getsCallTotalPrice() {
		return sCallTotalPrice;
	}


	public void setsCallTotalPrice(Integer sCallTotalPrice) {
		this.sCallTotalPrice = sCallTotalPrice;
	}


	public Double getsCallAvgPrice() {
		return sCallAvgPrice;
	}


	public void setsCallAvgPrice(Double sCallAvgPrice) {
		this.sCallAvgPrice = sCallAvgPrice;
	}


	public Integer getsCallDiff() {
		return sCallDiff;
	}


	public void setsCallDiff(Integer sCallDiff) {
		this.sCallDiff = sCallDiff;
	}


	public Integer getsPutOI() {
		return sPutOI;
	}


	public void setsPutOI(Integer sPutOI) {
		this.sPutOI = sPutOI;
	}


	public Integer getsPutTotalPrice() {
		return sPutTotalPrice;
	}


	public void setsPutTotalPrice(Integer sPutTotalPrice) {
		this.sPutTotalPrice = sPutTotalPrice;
	}


	public Double getsPutAvgPrice() {
		return sPutAvgPrice;
	}


	public void setsPutAvgPrice(Double sPutAvgPrice) {
		this.sPutAvgPrice = sPutAvgPrice;
	}


	public Integer getsPutDiff() {
		return sPutDiff;
	}


	public void setsPutDiff(Integer sPutDiff) {
		this.sPutDiff = sPutDiff;
	}



}
