package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Singal")
public class Singal extends BaseEntity {
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private String id;
	
	@Column(name = "content", length=1000)
	private String content;
	
	public Singal() {
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}


}
