package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockExclude")
public class StockExclude extends BaseEntity {
	@EmbeddedId
	private StockExcludeId id;
	
	/** 配息*/
	@Column(name = "excludeDividend")
	private Double excludeDividend;
	
	/** 配股*/
	@Column(name = "excludeRight")
	private Double excludeRight;
	
	/** 除權息日*/
	@Column(name = "excludeDate")
	private Date excludeDate;
	
	/** 現金殖利率*/
	@Column(name = "cashYields")
	private Double cashYields;
	
	/** 殖利率*/
	@Column(name = "yields")
	private Double yields;
	
	/** 配息率*/
	@Column(name = "couponRate")
	private Double couponRate;
	
	/** 除權後價格*/
	@Column(name = "afterExPrice")
	private Double afterExPrice;
	
	/** 除息趴數*/
	@Column(name = "excludeDividendRate")
	private Double excludeDividendRate;
	
	/** 除權趴數*/
	@Column(name = "excludeRightRate")
	private Double excludeRightRate;

	/** 除權息趴數*/
	@Column(name = "rdRate")
	private Double rdRate;
	
	/** 權息黃金比例*/
	@Column(name = "rdGoldRate")
	private Double rdGoldRate;

	/** 股票名稱*/
	@Column(name = "stockName")
	private String stockName;
	
	/** 當時價格*/
	@Column(name = "price")
	private Double price;
	
	@Transient
	private Integer futures;
	
	@Transient
	private Integer wants;
	
	public StockExclude() {
	}


	public StockExcludeId getId() {
		return id;
	}


	public void setId(StockExcludeId id) {
		this.id = id;
	}


	public Double getExcludeDividend() {
		return excludeDividend;
	}


	public void setExcludeDividend(Double excludeDividend) {
		this.excludeDividend = excludeDividend;
	}


	public Double getExcludeRight() {
		return excludeRight;
	}


	public void setExcludeRight(Double excludeRight) {
		this.excludeRight = excludeRight;
	}


	public Date getExcludeDate() {
		return excludeDate;
	}


	public void setExcludeDate(Date excludeDate) {
		this.excludeDate = excludeDate;
	}


	public Double getCashYields() {
		return cashYields;
	}


	public void setCashYields(Double cashYields) {
		this.cashYields = cashYields;
	}


	public Double getYields() {
		return yields;
	}


	public void setYields(Double yields) {
		this.yields = yields;
	}


	public Double getCouponRate() {
		return couponRate;
	}


	public void setCouponRate(Double couponRate) {
		this.couponRate = couponRate;
	}


	public Double getAfterExPrice() {
		return afterExPrice;
	}


	public void setAfterExPrice(Double afterExPrice) {
		this.afterExPrice = afterExPrice;
	}


	public Double getExcludeDividendRate() {
		return excludeDividendRate;
	}


	public void setExcludeDividendRate(Double excludeDividendRate) {
		this.excludeDividendRate = excludeDividendRate;
	}


	public Double getExcludeRightRate() {
		return excludeRightRate;
	}


	public void setExcludeRightRate(Double excludeRightRate) {
		this.excludeRightRate = excludeRightRate;
	}


	public Double getRdRate() {
		return rdRate;
	}


	public void setRdRate(Double rdRate) {
		this.rdRate = rdRate;
	}


	public Double getRdGoldRate() {
		return rdGoldRate;
	}


	public void setRdGoldRate(Double rdGoldRate) {
		this.rdGoldRate = rdGoldRate;
	}


	public String getStockName() {
		return stockName;
	}


	public void setStockName(String stockName) {
		this.stockName = stockName;
	}


	public Double getPrice() {
		return price;
	}


	public void setPrice(Double price) {
		this.price = price;
	}


	public Integer getFutures() {
		return futures;
	}


	public void setFutures(Integer futures) {
		this.futures = futures;
	}


	public Integer getWants() {
		return wants;
	}


	public void setWants(Integer wants) {
		this.wants = wants;
	}



}
