package com.stockapp.stockserver.entity;

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "warrants")
public class StockWants extends BaseEntity {
	@Id
    @Column(name = "warrant_code", length = 50)
    private String warrantCode;

    @Column(name = "warrant_abbr", length = 255)
    private String warrantAbbr;

    @Column(name = "underlying_code", length = 50)
    private String underlyingCode;

    @Column(name = "underlying_name", length = 255)
    private String underlyingName;

    @Column(name = "warrant_type", length = 50)
    private String warrantType;

    @Column(name = "exercise_method", length = 50)
    private String exerciseMethod;

    @Column(name = "listing_date")
    private String listingDate;

    @Column(name = "start_date")
    private String startDate;

    @Column(name = "end_trade_date")
    private String endTradeDate;

    @Column(name = "due_date")
    private String dueDate;

    @Column(name = "exercise_ratio", precision = 10, scale = 4)
    private BigDecimal exerciseRatio;

    @Column(name = "exercise_price", precision = 18, scale = 4)
    private BigDecimal exercisePrice;

	public String getWarrantCode() {
		return warrantCode;
	}

	public void setWarrantCode(String warrantCode) {
		this.warrantCode = warrantCode;
	}

	public String getWarrantAbbr() {
		return warrantAbbr;
	}

	public void setWarrantAbbr(String warrantAbbr) {
		this.warrantAbbr = warrantAbbr;
	}

	public String getUnderlyingCode() {
		return underlyingCode;
	}

	public void setUnderlyingCode(String underlyingCode) {
		this.underlyingCode = underlyingCode;
	}

	public String getUnderlyingName() {
		return underlyingName;
	}

	public void setUnderlyingName(String underlyingName) {
		this.underlyingName = underlyingName;
	}

	public String getWarrantType() {
		return warrantType;
	}

	public void setWarrantType(String warrantType) {
		this.warrantType = warrantType;
	}

	public String getExerciseMethod() {
		return exerciseMethod;
	}

	public void setExerciseMethod(String exerciseMethod) {
		this.exerciseMethod = exerciseMethod;
	}

	public String getListingDate() {
		return listingDate;
	}

	public void setListingDate(String listingDate) {
		this.listingDate = listingDate;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndTradeDate() {
		return endTradeDate;
	}

	public void setEndTradeDate(String endTradeDate) {
		this.endTradeDate = endTradeDate;
	}

	public String getDueDate() {
		return dueDate;
	}

	public void setDueDate(String dueDate) {
		this.dueDate = dueDate;
	}

	public BigDecimal getExerciseRatio() {
		return exerciseRatio;
	}

	public void setExerciseRatio(BigDecimal exerciseRatio) {
		this.exerciseRatio = exerciseRatio;
	}

	public BigDecimal getExercisePrice() {
		return exercisePrice;
	}

	public void setExercisePrice(BigDecimal exercisePrice) {
		this.exercisePrice = exercisePrice;
	}

}
