package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Stockai")
public class Stockai extends BaseEntity {
	@Id
	@Column(name = "dataTime", unique = true, nullable = false)
	private Long datetime;

	@Column(name = "stockId")
	private String stockId;

	@Column(name = "market")
	private String market;

	@Column(name = "aiContent")
	private String aiContent;

	public Long getDatetime() {
		return datetime;
	}

	public void setDatetime(Long datetime) {
		this.datetime = datetime;
	}

	public String getStockId() {
		return stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public String getMarket() {
		return market;
	}

	public void setMarket(String market) {
		this.market = market;
	}

	public String getAiContent() {
		return aiContent;
	}

	public void setAiContent(String aiContent) {
		this.aiContent = aiContent;
	}
	
	
}
