package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockDataMA")
public class StockDataMA extends BaseEntity {
	@EmbeddedId
	private StockDataId id;

	@Column(name = "ma3")
	private Double ma3;

	@Column(name = "ma5")
	private Double ma5;

	@Column(name = "ma8")
	private Double ma8;

	@Column(name = "ma10")
	private Double ma10;

	@Column(name = "ma20")
	private Double ma20;

	@Column(name = "ma60")
	private Double ma60;

	@Column(name = "ma13")
	private Double ma13;

	@Column(name = "ma21")
	private Double ma21;

	@Column(name = "ma34")
	private Double ma34;

	@Column(name = "ma55")
	private Double ma55;

	@Column(name = "ma89")
	private Double ma89;

	@Column(name = "ma144")
	private Double ma144;

	@Column(name = "ma233")
	private Double ma233;

	@Column(name = "dataDate")
	private Date dataDate;

	public StockDataMA() {
	}

	public StockDataId getId() {
		return id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

	public Double getMa3() {
		return ma3;
	}

	public void setMa3(Double ma3) {
		this.ma3 = ma3;
	}

	public Double getMa5() {
		return ma5;
	}

	public void setMa5(Double ma5) {
		this.ma5 = ma5;
	}

	public Double getMa8() {
		return ma8;
	}

	public void setMa8(Double ma8) {
		this.ma8 = ma8;
	}

	public Double getMa10() {
		return ma10;
	}

	public void setMa10(Double ma10) {
		this.ma10 = ma10;
	}

	public Double getMa13() {
		return ma13;
	}

	public void setMa13(Double ma13) {
		this.ma13 = ma13;
	}

	public Double getMa21() {
		return ma21;
	}

	public void setMa21(Double ma21) {
		this.ma21 = ma21;
	}

	public Double getMa34() {
		return ma34;
	}

	public void setMa34(Double ma34) {
		this.ma34 = ma34;
	}

	public Double getMa55() {
		return ma55;
	}

	public void setMa55(Double ma55) {
		this.ma55 = ma55;
	}

	public Double getMa89() {
		return ma89;
	}

	public void setMa89(Double ma89) {
		this.ma89 = ma89;
	}

	public Double getMa144() {
		return ma144;
	}

	public void setMa144(Double ma144) {
		this.ma144 = ma144;
	}

	public Double getMa233() {
		return ma233;
	}

	public void setMa233(Double ma233) {
		this.ma233 = ma233;
	}

	public Double getMa20() {
		return ma20;
	}

	public void setMa20(Double ma20) {
		this.ma20 = ma20;
	}

	public Double getMa60() {
		return ma60;
	}

	public void setMa60(Double ma60) {
		this.ma60 = ma60;
	}

	public Date getDataDate() {
		return dataDate;
	}

	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}

}
