package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockFutures")
public class StockFutures extends BaseEntity {
	@Id
	@Column(name = "stockId", unique = true, nullable = false, length = 50)
	private String stockId;
	
	@Column(name = "productId", nullable = false, length = 20)
	private String productId;
	
	@Column(name = "stockName", nullable = false, length = 100)
	private String stockName;
	
	@Column(name = "stockShortName", nullable = false, length = 50)
	private String stockShortName;

	@Column(name = "futuresTarget")
	private Integer futuresTarget;
	
	@Column(name = "optionsTarget")
	private Integer optionsTarget;

	public StockFutures() {
	}

	public String getStockId() {
		return stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getStockName() {
		return stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public Integer getFuturesTarget() {
		return futuresTarget;
	}

	public void setFuturesTarget(Integer futuresTarget) {
		this.futuresTarget = futuresTarget;
	}

	public Integer getOptionsTarget() {
		return optionsTarget;
	}

	public void setOptionsTarget(Integer optionsTarget) {
		this.optionsTarget = optionsTarget;
	}

	public String getStockShortName() {
		return stockShortName;
	}

	public void setStockShortName(String stockShortName) {
		this.stockShortName = stockShortName;
	}


}
