package com.stockapp.stockserver.entity;

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Stocks")
public class Stocks extends BaseEntity {
	// 目前id使用http://histock.tw/的代碼(No)
	@Id
	@Column(name = "stockId", unique = true, nullable = false, length = 50)
	private String stockId;

	@Column(name = "stockName", nullable = false, length = 100)
	private String stockName;

	@Column(name = "stockEngName", nullable = true, length = 200)
	private String stockEngName;

	@Column(name = "stockShortName", nullable = true, length = 50)
	private String stockShortName;

	@Column(name = "stockType", nullable = false, length = 10)
	private String stockType;

	@Column(name = "lastUpdateTime")
	private Date lastUpdateTime;

	@Column(name = "lastUpdateTimeHistock")
	private Date lastUpdateTimeHistock;

	/** 股票狀態 0:下市櫃 1:持續買賣 */
	@Column(name = "status")
	private Integer status;

	/** 有權證 */
	@Column(name = "wants")
	private Integer wants;

	/** 有期貨 */
	@Column(name = "futures")
	private Integer futures;

	/** 期貨代號 */
	@Column(name = "futuresId")
	private String futuresId;

	/** 原始保證金適用比例 */
	@Column(name = "originalRatio")
	private BigDecimal originalRatio;

	/** 期貨代號-小型 */
	@Column(name = "futuresId2")
	private String futuresId2;

	/** 原始保證金適用比例-小型 */
	@Column(name = "originalRatio2")
	private BigDecimal originalRatio2;

	/** 股本 */
	@Column(name = "capital")
	private BigDecimal capital;

	/** 產品 */
	@Column(name = "products", length = 500)
	private String products;
	
	

	public Stocks() {
	}

	public String getStockId() {
		return stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public String getStockName() {
		return stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getStockEngName() {
		return stockEngName;
	}

	public void setStockEngName(String stockEngName) {
		this.stockEngName = stockEngName;
	}

	public String getStockShortName() {
		return stockShortName;
	}

	public void setStockShortName(String stockShortName) {
		this.stockShortName = stockShortName;
	}

	public String getStockType() {
		return stockType;
	}

	public void setStockType(String stockType) {
		this.stockType = stockType;
	}

	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getWants() {
		return wants;
	}

	public void setWants(Integer wants) {
		this.wants = wants;
	}

	public Integer getFutures() {
		return futures;
	}

	public void setFutures(Integer futures) {
		this.futures = futures;
	}

	public Date getLastUpdateTimeHistock() {
		return lastUpdateTimeHistock;
	}

	public void setLastUpdateTimeHistock(Date lastUpdateTimeHistock) {
		this.lastUpdateTimeHistock = lastUpdateTimeHistock;
	}

	public String getFuturesId() {
		return futuresId;
	}

	public void setFuturesId(String futuresId) {
		this.futuresId = futuresId;
	}

	public BigDecimal getOriginalRatio() {
		return originalRatio;
	}

	public void setOriginalRatio(BigDecimal originalRatio) {
		this.originalRatio = originalRatio;
	}

	public String getFuturesId2() {
		return futuresId2;
	}

	public void setFuturesId2(String futuresId2) {
		this.futuresId2 = futuresId2;
	}

	public BigDecimal getOriginalRatio2() {
		return originalRatio2;
	}

	public void setOriginalRatio2(BigDecimal originalRatio2) {
		this.originalRatio2 = originalRatio2;
	}

	public String getProducts() {
		return products;
	}

	public void setProducts(String products) {
		this.products = products;
	}

	public BigDecimal getCapital() {
		return capital;
	}

	public void setCapital(BigDecimal capital) {
		this.capital = capital;
	}

}
