package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockDataTurtul")
public class StockDataTurtle extends BaseEntity {
	@EmbeddedId
	private StockDataId id;



	@Column(name = "trueRange")
	private Double trueRange;

	/** 也就是N */
	@Column(name = "averageTrueRange")
	private Double averageTrueRange;

	@Column(name = "dataDate")
	private Date dataDate;

	public StockDataTurtle() {
	}

	public StockDataId getId() {
		return id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

	public Date getDataDate() {
		return dataDate;
	}

	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}

	public Double getTrueRange() {
		return trueRange;
	}

	public void setTrueRange(Double trueRange) {
		this.trueRange = trueRange;
	}

	public Double getAverageTrueRange() {
		return averageTrueRange;
	}

	public void setAverageTrueRange(Double averageTrueRange) {
		this.averageTrueRange = averageTrueRange;
	}

}
