package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockDataRSI")
public class StockDataRSI extends BaseEntity {
	@EmbeddedId
	private StockDataId id;

	@Column(name = "rsi6")
	private Double rsi6;

	@Column(name = "rsi12")
	private Double rsi12;

	@Column(name = "k9")
	private Double k9;

	@Column(name = "d9")
	private Double d9;

	public StockDataId getId() {
		return id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

	public Double getRsi6() {
		return rsi6;
	}

	public void setRsi6(Double rsi6) {
		this.rsi6 = rsi6;
	}

	public Double getRsi12() {
		return rsi12;
	}

	public void setRsi12(Double rsi12) {
		this.rsi12 = rsi12;
	}

	public Double getK9() {
		return k9;
	}

	public void setK9(Double k9) {
		this.k9 = k9;
	}

	public Double getD9() {
		return d9;
	}

	public void setD9(Double d9) {
		this.d9 = d9;
	}

}
