package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockDataEMA")
public class StockDataEMA extends BaseEntity {
	@EmbeddedId
	private StockDataId id;

	@Column(name = "ema3")
	private Double ema3;

	@Column(name = "ema5")
	private Double ema5;

	@Column(name = "ema7")
	private Double ema7;

	@Column(name = "ema8")
	private Double ema8;

	@Column(name = "ema10")
	private Double ema10;

	@Column(name = "ema20")
	private Double ema20;

	@Column(name = "ema60")
	private Double ema60;

	@Column(name = "ema13")
	private Double ema13;

	@Column(name = "ema21")
	private Double ema21;

	@Column(name = "ema34")
	private Double ema34;

	@Column(name = "ema53")
	private Double ema53;

	@Column(name = "ema55")
	private Double ema55;

	@Column(name = "ema89")
	private Double ema89;

	@Column(name = "ema144")
	private Double ema144;

	@Column(name = "ema233")
	private Double ema233;

	@Column(name = "dataDate")
	private Date dataDate;

	public StockDataEMA() {
	}

	public StockDataId getId() {
		return id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

	public Double getEma5() {
		return ema5;
	}

	public void setEma5(Double ema5) {
		this.ema5 = ema5;
	}

	public Double getEma7() {
		return ema7;
	}

	public void setEma7(Double ema7) {
		this.ema7 = ema7;
	}

	public Double getEma8() {
		return ema8;
	}

	public void setEma8(Double ema8) {
		this.ema8 = ema8;
	}

	public Double getEma13() {
		return ema13;
	}

	public void setEma13(Double ema13) {
		this.ema13 = ema13;
	}

	public Double getEma21() {
		return ema21;
	}

	public void setEma21(Double ema21) {
		this.ema21 = ema21;
	}

	public Double getEma34() {
		return ema34;
	}

	public void setEma34(Double ema34) {
		this.ema34 = ema34;
	}

	public Double getEma53() {
		return ema53;
	}

	public void setEma53(Double ema53) {
		this.ema53 = ema53;
	}

	public Double getEma55() {
		return ema55;
	}

	public void setEma55(Double ema55) {
		this.ema55 = ema55;
	}

	public Double getEma89() {
		return ema89;
	}

	public void setEma89(Double ema89) {
		this.ema89 = ema89;
	}

	public Double getEma144() {
		return ema144;
	}

	public void setEma144(Double ema144) {
		this.ema144 = ema144;
	}

	public Double getEma233() {
		return ema233;
	}

	public void setEma233(Double ema233) {
		this.ema233 = ema233;
	}

	public Date getDataDate() {
		return dataDate;
	}

	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}

	public Double getEma3() {
		return ema3;
	}

	public void setEma3(Double ema3) {
		this.ema3 = ema3;
	}

	public Double getEma10() {
		return ema10;
	}

	public void setEma10(Double ema10) {
		this.ema10 = ema10;
	}

	public Double getEma20() {
		return ema20;
	}

	public void setEma20(Double ema20) {
		this.ema20 = ema20;
	}

	public Double getEma60() {
		return ema60;
	}

	public void setEma60(Double ema60) {
		this.ema60 = ema60;
	}

}
