package com.stockapp.stockserver.entity;

import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.ConstraintMode;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockData")
public class StockData extends BaseEntity {
	@EmbeddedId
	private StockDataId id;
	
	@Column(name = "open")
	private Double open;
	
	@Column(name = "close")
	private Double close;
	
	@Column(name = "high")
	private Double high;
	
	@Column(name = "low")
	private Double low;
	
	@Column(name = "volume")
	private Integer volume;
	
	@Column(name = "volume2")
	private Integer volume2;
	
	@Column(name = "dataDate")
	private LocalDateTime dataDate;

	@Transient
	private String dateString;

	@OneToOne(cascade=CascadeType.REMOVE)
	@PrimaryKeyJoinColumn(foreignKey = @ForeignKey(value = ConstraintMode.NO_CONSTRAINT))
	private StockDataMA ma;
	
	@OneToOne(cascade=CascadeType.REMOVE)
	@PrimaryKeyJoinColumn(foreignKey = @ForeignKey(value = ConstraintMode.NO_CONSTRAINT))
	private StockDataEMA ema;
	
	public StockData() {
	}
	
	public String getDateString() {
		if(dataDate == null) {
			return "";
		}
		
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
		return dataDate.format(DateTimeFormatter.ofPattern("yyyy/MM/dd"));
	}

	public void setDateString(String dateString) {
		this.dateString = dateString;
	}

	public StockDataId getId() {
		return id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

	public Double getOpen() {
		return open;
	}

	public void setOpen(Double open) {
		this.open = open;
	}

	public Double getClose() {
		return close;
	}

	public void setClose(Double close) {
		this.close = close;
	}

	public Double getHigh() {
		return high;
	}

	public void setHigh(Double high) {
		this.high = high;
	}

	public Double getLow() {
		return low;
	}

	public void setLow(Double low) {
		this.low = low;
	}

	public Integer getVolume() {
		return volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	public Integer getVolume2() {
		return volume2;
	}

	public void setVolume2(Integer volume2) {
		this.volume2 = volume2;
	}

	public LocalDateTime getDataDate() {
		return dataDate;
	}

	public void setDataDate(LocalDateTime dataDate) {
		this.dataDate = dataDate;
	}

	public StockDataMA getMa() {
		return ma;
	}

	public void setMa(StockDataMA ma) {
		this.ma = ma;
	}

	public StockDataEMA getEma() {
		return ema;
	}

	public void setEma(StockDataEMA ema) {
		this.ema = ema;
	}
}
