package com.stockapp.stockserver.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockPriceLevel")
public class StockPriceLevel extends BaseEntity {
	@EmbeddedId
	private StockDataId id;

	@Column(name = "dataDate")
	private LocalDateTime dataDate;

	@Column(name = "h12")
	private Double h12;

	@Column(name = "l12")
	private Double l12;
	
	/** 買耗 */
	@Column(name = "level1")
	private Double level1;

	/** 嘎空 */
	@Column(name = "level2")
	private Double level2;

	/** 轉強 */
	@Column(name = "level3")
	private Double level3;

	/** 中軸 */
	@Column(name = "level4")
	private Double level4;

	/** 回撐 */
	@Column(name = "level5")
	private Double level5;

	/** 轉弱 */
	@Column(name = "level6")
	private Double level6;

	/** 殺多 */
	@Column(name = "level7")
	private Double level7;

	/** 賣耗 */
	@Column(name = "level8")
	private Double level8;

	/** 多空線 */
	@Column(name = "level9")
	private Double level9;

	/** 轉折 */
	@Column(name = "turn")
	private Double turn;

	public StockDataId getId() {
		return id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

	public Double getLevel1() {
		return level1;
	}

	public void setLevel1(Double level1) {
		this.level1 = level1;
	}

	public Double getLevel2() {
		return level2;
	}

	public void setLevel2(Double level2) {
		this.level2 = level2;
	}

	public Double getLevel3() {
		return level3;
	}

	public void setLevel3(Double level3) {
		this.level3 = level3;
	}

	public Double getLevel4() {
		return level4;
	}

	public void setLevel4(Double level4) {
		this.level4 = level4;
	}

	public Double getLevel5() {
		return level5;
	}

	public void setLevel5(Double level5) {
		this.level5 = level5;
	}

	public Double getLevel6() {
		return level6;
	}

	public void setLevel6(Double level6) {
		this.level6 = level6;
	}

	public Double getLevel7() {
		return level7;
	}

	public void setLevel7(Double level7) {
		this.level7 = level7;
	}

	public Double getLevel8() {
		return level8;
	}

	public void setLevel8(Double level8) {
		this.level8 = level8;
	}

	public Double getLevel9() {
		return level9;
	}

	public void setLevel9(Double level9) {
		this.level9 = level9;
	}

	public Double getTurn() {
		return turn;
	}

	public void setTurn(Double turn) {
		this.turn = turn;
	}

	public LocalDateTime getDataDate() {
		return dataDate;
	}

	public void setDataDate(LocalDateTime dataDate) {
		this.dataDate = dataDate;
	}

	public Double getH12() {
		return h12;
	}

	public void setH12(Double h12) {
		this.h12 = h12;
	}

	public Double getL12() {
		return l12;
	}

	public void setL12(Double l12) {
		this.l12 = l12;
	}

}
