package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockBuySell")
public class StockBuySell extends BaseEntity {
	@EmbeddedId
	private StockBuySellId id;

	@Column(name = "dataDate")
	private Date dataDate;

	/** 買點1 */
	@Column(name = "buy1")
	private int buy1 = 0;

	/** 買點2 */
	@Column(name = "buy2")
	private int buy2 = 0;

	/** 買點3 */
	@Column(name = "buy3")
	private int buy3 = 0;

	/** 買點4 */
	@Column(name = "buy4")
	private int buy4 = 0;

	/** 賣點1 */
	@Column(name = "sell1")
	private int sell1 = 0;

	/** 賣點2 */
	@Column(name = "sell2")
	private int sell2 = 0;

	/** 賣點3 */
	@Column(name = "sell3")
	private int sell3 = 0;

	/** 賣點4 */
	@Column(name = "sell4")
	private int sell4 = 0;

	/** 多頭排列 */
	@Column(name = "u1")
	private int u1 = 0;

	/** 7、13金叉 */
	@Column(name = "u2")
	private int u2 = 0;

	/** 7、21金叉 */
	@Column(name = "u3")
	private int u3 = 0;

	/** 7、53金叉 */
	@Column(name = "u4")
	private int u4 = 0;

	/** 13、21金叉 */
	@Column(name = "u5")
	private int u5 = 0;

	/** 13、53金叉 */
	@Column(name = "u6")
	private int u6 = 0;

	/** 21、53金叉 */
	@Column(name = "u7")
	private int u7 = 0;

	/** 空頭排列 */
	@Column(name = "d1")
	private int d1 = 0;

	/** 7、13死叉 */
	@Column(name = "d2")
	private int d2 = 0;

	/** 7、21死叉 */
	@Column(name = "d3")
	private int d3 = 0;

	/** 7、53死叉 */
	@Column(name = "d4")
	private int d4 = 0;

	/** 13、21死叉 */
	@Column(name = "d5")
	private int d5 = 0;

	/** 13、53死叉 */
	@Column(name = "d6")
	private int d6 = 0;

	/** 21、53死叉 */
	@Column(name = "d7")
	private int d7 = 0;

	public StockBuySell() {
	}

	public StockBuySellId getId() {
		return id;
	}

	public void setId(StockBuySellId id) {
		this.id = id;
	}

	public Date getDataDate() {
		return dataDate;
	}

	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}

	public int getBuy1() {
		return buy1;
	}

	public void setBuy1(int buy1) {
		this.buy1 = buy1;
	}

	public int getBuy2() {
		return buy2;
	}

	public void setBuy2(int buy2) {
		this.buy2 = buy2;
	}

	public int getBuy3() {
		return buy3;
	}

	public void setBuy3(int buy3) {
		this.buy3 = buy3;
	}

	public int getBuy4() {
		return buy4;
	}

	public void setBuy4(int buy4) {
		this.buy4 = buy4;
	}

	public int getSell1() {
		return sell1;
	}

	public void setSell1(int sell1) {
		this.sell1 = sell1;
	}

	public int getSell2() {
		return sell2;
	}

	public void setSell2(int sell2) {
		this.sell2 = sell2;
	}

	public int getSell3() {
		return sell3;
	}

	public void setSell3(int sell3) {
		this.sell3 = sell3;
	}

	public int getSell4() {
		return sell4;
	}

	public void setSell4(int sell4) {
		this.sell4 = sell4;
	}

	public int getU1() {
		return u1;
	}

	public void setU1(int u1) {
		this.u1 = u1;
	}

	public int getU2() {
		return u2;
	}

	public void setU2(int u2) {
		this.u2 = u2;
	}

	public int getU3() {
		return u3;
	}

	public void setU3(int u3) {
		this.u3 = u3;
	}

	public int getU4() {
		return u4;
	}

	public void setU4(int u4) {
		this.u4 = u4;
	}

	public int getU5() {
		return u5;
	}

	public void setU5(int u5) {
		this.u5 = u5;
	}

	public int getU6() {
		return u6;
	}

	public void setU6(int u6) {
		this.u6 = u6;
	}

	public int getU7() {
		return u7;
	}

	public void setU7(int u7) {
		this.u7 = u7;
	}

	public int getD1() {
		return d1;
	}

	public void setD1(int d1) {
		this.d1 = d1;
	}

	public int getD2() {
		return d2;
	}

	public void setD2(int d2) {
		this.d2 = d2;
	}

	public int getD3() {
		return d3;
	}

	public void setD3(int d3) {
		this.d3 = d3;
	}

	public int getD4() {
		return d4;
	}

	public void setD4(int d4) {
		this.d4 = d4;
	}

	public int getD5() {
		return d5;
	}

	public void setD5(int d5) {
		this.d5 = d5;
	}

	public int getD6() {
		return d6;
	}

	public void setD6(int d6) {
		this.d6 = d6;
	}

	public int getD7() {
		return d7;
	}

	public void setD7(int d7) {
		this.d7 = d7;
	}

}
