package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockDataTurn")
public class StockDataTurn extends BaseEntity {
	@EmbeddedId
	private StockDataId id;

	//日多空中軸
	@Column
	private Double middle;

	//DD開盤破站不上空
	@Column
	private Double value1;

	//易多空線
	@Column
	private Double value2;

	//超強
	@Column
	private Double value3;

	//乖離短賣
	@Column
	private Double value4;

	//高控多停利
	@Column
	private Double value5;

	//低控空回補
	@Column
	private Double value6;

	//嘎空點
	@Column
	private Double value7;

	//D殺多
	@Column
	private Double value8;

	//末跌
	@Column
	private Double value9;

	//日續跌
	@Column
	private Double value10;

	//破續跌續空
	@Column
	private Double value11;

	//碰主跌=搶短點
	@Column
	private Double value12;

	//碰主跌3
	@Column
	private Double value14;

	//彈仍跌(放空)
	@Column
	private Double value15;

	//回跌
	@Column
	private Double value16;

	//回檔買點/反彈賣點
	@Column
	private Double value17;

	//時K反彈不該過中軸
	@Column
	private Double value18;

	//盤跌
	@Column
	private Double value19;

	//T盤漲
	@Column
	private Double value20;

	//反彈峰B
	@Column
	private Double value21;

	//續漲-不破續多
	@Column
	private Double value22;

	//過起漲3
	@Column
	private Double value23;

	//過起漲
	@Column
	private Double value24;

	//日續漲
	@Column
	private Double value25;

	//主升
	@Column
	private Double value26;

	//強波2000點
	@Column
	private Double value27;

	//超跌17
	@Column
	private Double value29;

	//超跌16
	@Column
	private Double value30;

	//超跌15
	@Column
	private Double value31;

	public StockDataId getId() {
		return id;
	}

	public void setId(StockDataId id) {
		this.id = id;
	}

	public Double getMiddle() {
		return middle;
	}

	public void setMiddle(Double middle) {
		this.middle = middle;
	}

	public Double getValue1() {
		return value1;
	}

	public void setValue1(Double value1) {
		this.value1 = value1;
	}

	public Double getValue2() {
		return value2;
	}

	public void setValue2(Double value2) {
		this.value2 = value2;
	}

	public Double getValue3() {
		return value3;
	}

	public void setValue3(Double value3) {
		this.value3 = value3;
	}

	public Double getValue4() {
		return value4;
	}

	public void setValue4(Double value4) {
		this.value4 = value4;
	}

	public Double getValue5() {
		return value5;
	}

	public void setValue5(Double value5) {
		this.value5 = value5;
	}

	public Double getValue6() {
		return value6;
	}

	public void setValue6(Double value6) {
		this.value6 = value6;
	}

	public Double getValue7() {
		return value7;
	}

	public void setValue7(Double value7) {
		this.value7 = value7;
	}

	public Double getValue8() {
		return value8;
	}

	public void setValue8(Double value8) {
		this.value8 = value8;
	}

	public Double getValue9() {
		return value9;
	}

	public void setValue9(Double value9) {
		this.value9 = value9;
	}

	public Double getValue10() {
		return value10;
	}

	public void setValue10(Double value10) {
		this.value10 = value10;
	}

	public Double getValue11() {
		return value11;
	}

	public void setValue11(Double value11) {
		this.value11 = value11;
	}

	public Double getValue12() {
		return value12;
	}

	public void setValue12(Double value12) {
		this.value12 = value12;
	}

	public Double getValue14() {
		return value14;
	}

	public void setValue14(Double value14) {
		this.value14 = value14;
	}

	public Double getValue15() {
		return value15;
	}

	public void setValue15(Double value15) {
		this.value15 = value15;
	}

	public Double getValue16() {
		return value16;
	}

	public void setValue16(Double value16) {
		this.value16 = value16;
	}

	public Double getValue17() {
		return value17;
	}

	public void setValue17(Double value17) {
		this.value17 = value17;
	}

	public Double getValue18() {
		return value18;
	}

	public void setValue18(Double value18) {
		this.value18 = value18;
	}

	public Double getValue19() {
		return value19;
	}

	public void setValue19(Double value19) {
		this.value19 = value19;
	}

	public Double getValue20() {
		return value20;
	}

	public void setValue20(Double value20) {
		this.value20 = value20;
	}

	public Double getValue21() {
		return value21;
	}

	public void setValue21(Double value21) {
		this.value21 = value21;
	}

	public Double getValue22() {
		return value22;
	}

	public void setValue22(Double value22) {
		this.value22 = value22;
	}

	public Double getValue23() {
		return value23;
	}

	public void setValue23(Double value23) {
		this.value23 = value23;
	}

	public Double getValue24() {
		return value24;
	}

	public void setValue24(Double value24) {
		this.value24 = value24;
	}

	public Double getValue25() {
		return value25;
	}

	public void setValue25(Double value25) {
		this.value25 = value25;
	}

	public Double getValue26() {
		return value26;
	}

	public void setValue26(Double value26) {
		this.value26 = value26;
	}

	public Double getValue27() {
		return value27;
	}

	public void setValue27(Double value27) {
		this.value27 = value27;
	}

	public Double getValue29() {
		return value29;
	}

	public void setValue29(Double value29) {
		this.value29 = value29;
	}

	public Double getValue30() {
		return value30;
	}

	public void setValue30(Double value30) {
		this.value30 = value30;
	}

	public Double getValue31() {
		return value31;
	}

	public void setValue31(Double value31) {
		this.value31 = value31;
	}

}
