package com.stockapp.stockserver.entity;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "StockGap")
public class StockGap extends BaseEntity {
	@EmbeddedId
	private StockGapId id;
	
	/** 缺口型態  1-跳上 2-跳下*/
	@Column(name = "gapType", nullable = false, length = 10)
	private String gapType;
	
	@Column(name = "up")
	private Double up;
	
	@Column(name = "down")
	private Double down;
	
	@Column(name = "dataDate")
	private Date dataDate;
	
	
	public StockGap() {
	}




	public String getGapType() {
		return gapType;
	}




	public void setGapType(String gapType) {
		this.gapType = gapType;
	}




	public Double getUp() {
		return up;
	}




	public void setUp(Double up) {
		this.up = up;
	}




	public Double getDown() {
		return down;
	}




	public void setDown(Double down) {
		this.down = down;
	}




	public StockGapId getId() {
		return id;
	}




	public void setId(StockGapId id) {
		this.id = id;
	}




	public Date getDataDate() {
		return dataDate;
	}




	public void setDataDate(Date dataDate) {
		this.dataDate = dataDate;
	}


}
