package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "SystemParam")
public class SystemParam extends BaseEntity {
	@Id
	@Column(name = "key", unique = true, nullable = false, length = 50)
	private String key;
	
	@Column(name = "value1", nullable = false, length = 50)
	private String value1;
	
	@Column(name = "value2", nullable = true, length = 100)
	private String value2;
	
	@Column(name = "desc", nullable = true, length = 500)
	private String desc;

	public SystemParam() {
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue1() {
		return value1;
	}

	public void setValue1(String value1) {
		this.value1 = value1;
	}

	public String getValue2() {
		return value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
