package com.stockapp.stockserver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * Book generated by hbm2java
 */
@Embeddable
public class WebhookId extends BaseEntity {
	@Column(name = "market")
    private String market;

    @Column(name = "id")
    private String id;

	public String getMarket() {
		return market;
	}

	public void setMarket(String market) {
		this.market = market;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
    
    
}
