package com.stockapp.stockserver.entity;

import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Webhook")
public class Webhook extends BaseEntity {
	@EmbeddedId
    private WebhookId webhookId;

	public WebhookId getWebhookId() {
		return webhookId;
	}

	public void setWebhookId(WebhookId webhookId) {
		this.webhookId = webhookId;
	}
	
}
